[package]
name = "agb_play"
version = "0.1.0"
authors = ["Tim Nibert"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
agb = "0.12.1"
bare-metal = "1"

[profile.dev]
opt-level = 2
debug = true

[profile.release]
panic = "abort"
lto = true
debug = true
